#include "includes/lsp.hpp"

#define COMPLETION_REQUIRE_ITEMS { \
(lsp::CompletionItem) { .label = "reqMarkupText", .insertText = "const MarkupText = require('dw/content/MarkupText');" }, \
(lsp::CompletionItem) { .label = "reqReturnHooks", .insertText = "const ReturnHooks = require('dw/order/hooks/ReturnHooks');" }, \
(lsp::CompletionItem) { .label = "reqBigInteger", .insertText = "const BigInteger = require('dw/util/BigInteger');" }, \
(lsp::CompletionItem) { .label = "reqJWS", .insertText = "const JWS = require('dw/crypto/JWS');" }, \
(lsp::CompletionItem) { .label = "reqMappingMgr", .insertText = "const MappingMgr = require('dw/util/MappingMgr');" }, \
(lsp::CompletionItem) { .label = "reqOrderHistory", .insertText = "const OrderHistory = require('dw/customer/OrderHistory');" }, \
(lsp::CompletionItem) { .label = "reqTrackingInfo", .insertText = "const TrackingInfo = require('dw/order/TrackingInfo');" }, \
(lsp::CompletionItem) { .label = "reqCatalogMgr", .insertText = "const CatalogMgr = require('dw/catalog/CatalogMgr');" }, \
(lsp::CompletionItem) { .label = "reqFocalPoint", .insertText = "const FocalPoint = require('dw/experience/image/FocalPoint');" }, \
(lsp::CompletionItem) { .label = "reqCustomerPasswordConstraints", .insertText = "const CustomerPasswordConstraints = require('dw/customer/CustomerPasswordConstraints');" }, \
(lsp::CompletionItem) { .label = "reqCouponLineItem", .insertText = "const CouponLineItem = require('dw/order/CouponLineItem');" }, \
(lsp::CompletionItem) { .label = "reqXMLStreamReader", .insertText = "const XMLStreamReader = require('dw/io/XMLStreamReader');" }, \
(lsp::CompletionItem) { .label = "reqCustomerPaymentInstrument", .insertText = "const CustomerPaymentInstrument = require('dw/customer/CustomerPaymentInstrument');" }, \
(lsp::CompletionItem) { .label = "reqOrderAddress", .insertText = "const OrderAddress = require('dw/order/OrderAddress');" }, \
(lsp::CompletionItem) { .label = "reqTaxItem", .insertText = "const TaxItem = require('dw/order/TaxItem');" }, \
(lsp::CompletionItem) { .label = "reqFormField", .insertText = "const FormField = require('dw/web/FormField');" }, \
(lsp::CompletionItem) { .label = "reqCSRFProtection", .insertText = "const CSRFProtection = require('dw/web/CSRFProtection');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedContent", .insertText = "const SuggestedContent = require('dw/suggest/SuggestedContent');" }, \
(lsp::CompletionItem) { .label = "reqPaymentMgr", .insertText = "const PaymentMgr = require('dw/order/PaymentMgr');" }, \
(lsp::CompletionItem) { .label = "reqProductListItem", .insertText = "const ProductListItem = require('dw/customer/ProductListItem');" }, \
(lsp::CompletionItem) { .label = "reqProductListRegistrant", .insertText = "const ProductListRegistrant = require('dw/customer/ProductListRegistrant');" }, \
(lsp::CompletionItem) { .label = "reqTemplate", .insertText = "const Template = require('dw/util/Template');" }, \
(lsp::CompletionItem) { .label = "reqEnumValue", .insertText = "const EnumValue = require('dw/value/EnumValue');" }, \
(lsp::CompletionItem) { .label = "reqAgentUserStatusCodes", .insertText = "const AgentUserStatusCodes = require('dw/customer/AgentUserStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqPropertyComparator", .insertText = "const PropertyComparator = require('dw/util/PropertyComparator');" }, \
(lsp::CompletionItem) { .label = "reqPaymentMethod", .insertText = "const PaymentMethod = require('dw/order/PaymentMethod');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentMethod", .insertText = "const SalesforcePaymentMethod = require('dw/extensions/payments/SalesforcePaymentMethod');" }, \
(lsp::CompletionItem) { .label = "reqCustomerActiveData", .insertText = "const CustomerActiveData = require('dw/customer/CustomerActiveData');" }, \
(lsp::CompletionItem) { .label = "reqCouponStatusCodes", .insertText = "const CouponStatusCodes = require('dw/campaign/CouponStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqFixedPriceShippingDiscount", .insertText = "const FixedPriceShippingDiscount = require('dw/campaign/FixedPriceShippingDiscount');" }, \
(lsp::CompletionItem) { .label = "reqPaymentRequestHookResult", .insertText = "const PaymentRequestHookResult = require('dw/extensions/paymentrequest/PaymentRequestHookResult');" }, \
(lsp::CompletionItem) { .label = "reqContentSearchRefinements", .insertText = "const ContentSearchRefinements = require('dw/content/ContentSearchRefinements');" }, \
(lsp::CompletionItem) { .label = "reqServiceDefinition", .insertText = "const ServiceDefinition = require('dw/svc/ServiceDefinition');" }, \
(lsp::CompletionItem) { .label = "reqCMSRecord", .insertText = "const CMSRecord = require('dw/experience/cms/CMSRecord');" }, \
(lsp::CompletionItem) { .label = "reqSet", .insertText = "const Set = require('dw/util/Set');" }, \
(lsp::CompletionItem) { .label = "reqProductPriceModel", .insertText = "const ProductPriceModel = require('dw/catalog/ProductPriceModel');" }, \
(lsp::CompletionItem) { .label = "reqProductVariationAttribute", .insertText = "const ProductVariationAttribute = require('dw/catalog/ProductVariationAttribute');" }, \
(lsp::CompletionItem) { .label = "reqFormFieldOption", .insertText = "const FormFieldOption = require('dw/web/FormFieldOption');" }, \
(lsp::CompletionItem) { .label = "reqServiceCallback", .insertText = "const ServiceCallback = require('dw/svc/ServiceCallback');" }, \
(lsp::CompletionItem) { .label = "reqCategory", .insertText = "const Category = require('dw/catalog/Category');" }, \
(lsp::CompletionItem) { .label = "reqStoreMgr", .insertText = "const StoreMgr = require('dw/catalog/StoreMgr');" }, \
(lsp::CompletionItem) { .label = "reqLocalServiceRegistry", .insertText = "const LocalServiceRegistry = require('dw/svc/LocalServiceRegistry');" }, \
(lsp::CompletionItem) { .label = "reqPageMetaTag", .insertText = "const PageMetaTag = require('dw/web/PageMetaTag');" }, \
(lsp::CompletionItem) { .label = "reqFormListItem", .insertText = "const FormListItem = require('dw/web/FormListItem');" }, \
(lsp::CompletionItem) { .label = "reqApproachingDiscount", .insertText = "const ApproachingDiscount = require('dw/campaign/ApproachingDiscount');" }, \
(lsp::CompletionItem) { .label = "reqShippingMgr", .insertText = "const ShippingMgr = require('dw/order/ShippingMgr');" }, \
(lsp::CompletionItem) { .label = "reqURL", .insertText = "const URL = require('dw/web/URL');" }, \
(lsp::CompletionItem) { .label = "reqRequestHooks", .insertText = "const RequestHooks = require('dw/system/RequestHooks');" }, \
(lsp::CompletionItem) { .label = "reqWebDAVFileInfo", .insertText = "const WebDAVFileInfo = require('dw/net/WebDAVFileInfo');" }, \
(lsp::CompletionItem) { .label = "reqLibrary", .insertText = "const Library = require('dw/content/Library');" }, \
(lsp::CompletionItem) { .label = "reqCoupon", .insertText = "const Coupon = require('dw/campaign/Coupon');" }, \
(lsp::CompletionItem) { .label = "reqSourceCodeInfo", .insertText = "const SourceCodeInfo = require('dw/campaign/SourceCodeInfo');" }, \
(lsp::CompletionItem) { .label = "reqPercentageDiscount", .insertText = "const PercentageDiscount = require('dw/campaign/PercentageDiscount');" }, \
(lsp::CompletionItem) { .label = "reqExtensible", .insertText = "const Extensible = require('dw/object/Extensible');" }, \
(lsp::CompletionItem) { .label = "reqTransaction", .insertText = "const Transaction = require('dw/system/Transaction');" }, \
(lsp::CompletionItem) { .label = "reqWriter", .insertText = "const Writer = require('dw/io/Writer');" }, \
(lsp::CompletionItem) { .label = "reqForms", .insertText = "const Forms = require('dw/web/Forms');" }, \
(lsp::CompletionItem) { .label = "reqAgentUserStatusCodes", .insertText = "const AgentUserStatusCodes = require('dw/system/AgentUserStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqAgentUserMgr", .insertText = "const AgentUserMgr = require('dw/customer/AgentUserMgr');" }, \
(lsp::CompletionItem) { .label = "reqPriceBookMgr", .insertText = "const PriceBookMgr = require('dw/catalog/PriceBookMgr');" }, \
(lsp::CompletionItem) { .label = "reqShippingOrderHooks", .insertText = "const ShippingOrderHooks = require('dw/order/hooks/ShippingOrderHooks');" }, \
(lsp::CompletionItem) { .label = "reqSourceCodeStatusCodes", .insertText = "const SourceCodeStatusCodes = require('dw/campaign/SourceCodeStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqProductAvailabilityModel", .insertText = "const ProductAvailabilityModel = require('dw/catalog/ProductAvailabilityModel');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePayPalOrderPayer", .insertText = "const SalesforcePayPalOrderPayer = require('dw/extensions/payments/SalesforcePayPalOrderPayer');" }, \
(lsp::CompletionItem) { .label = "reqWeakMessageDigest", .insertText = "const WeakMessageDigest = require('dw/crypto/WeakMessageDigest');" }, \
(lsp::CompletionItem) { .label = "reqLoopIterator", .insertText = "const LoopIterator = require('dw/web/LoopIterator');" }, \
(lsp::CompletionItem) { .label = "reqAlerts", .insertText = "const Alerts = require('dw/alert/Alerts');" }, \
(lsp::CompletionItem) { .label = "reqReturnItem", .insertText = "const ReturnItem = require('dw/order/ReturnItem');" }, \
(lsp::CompletionItem) { .label = "reqProductInventoryRecord", .insertText = "const ProductInventoryRecord = require('dw/catalog/ProductInventoryRecord');" }, \
(lsp::CompletionItem) { .label = "reqClickStream", .insertText = "const ClickStream = require('dw/web/ClickStream');" }, \
(lsp::CompletionItem) { .label = "reqStore", .insertText = "const Store = require('dw/catalog/Store');" }, \
(lsp::CompletionItem) { .label = "reqSortingOption", .insertText = "const SortingOption = require('dw/catalog/SortingOption');" }, \
(lsp::CompletionItem) { .label = "reqArrayList", .insertText = "const ArrayList = require('dw/util/ArrayList');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentsMgr", .insertText = "const SalesforcePaymentsMgr = require('dw/extensions/payments/SalesforcePaymentsMgr');" }, \
(lsp::CompletionItem) { .label = "reqPipelineDictionary", .insertText = "const PipelineDictionary = require('dw/system/PipelineDictionary');" }, \
(lsp::CompletionItem) { .label = "reqProductLineItem", .insertText = "const ProductLineItem = require('dw/order/ProductLineItem');" }, \
(lsp::CompletionItem) { .label = "reqProductSearchModel", .insertText = "const ProductSearchModel = require('dw/catalog/ProductSearchModel');" }, \
(lsp::CompletionItem) { .label = "reqProductShippingCost", .insertText = "const ProductShippingCost = require('dw/order/ProductShippingCost');" }, \
(lsp::CompletionItem) { .label = "reqProduct", .insertText = "const Product = require('dw/catalog/Product');" }, \
(lsp::CompletionItem) { .label = "reqPinterestFeedHooks", .insertText = "const PinterestFeedHooks = require('dw/extensions/pinterest/PinterestFeedHooks');" }, \
(lsp::CompletionItem) { .label = "reqExtensibleObject", .insertText = "const ExtensibleObject = require('dw/object/ExtensibleObject');" }, \
(lsp::CompletionItem) { .label = "reqSearchRefinementValue", .insertText = "const SearchRefinementValue = require('dw/catalog/SearchRefinementValue');" }, \
(lsp::CompletionItem) { .label = "reqCustomEditorResources", .insertText = "const CustomEditorResources = require('dw/experience/CustomEditorResources');" }, \
(lsp::CompletionItem) { .label = "reqPaymentStatusCodes", .insertText = "const PaymentStatusCodes = require('dw/order/PaymentStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqComponent", .insertText = "const Component = require('dw/experience/Component');" }, \
(lsp::CompletionItem) { .label = "reqJobProcessMonitor", .insertText = "const JobProcessMonitor = require('dw/system/JobProcessMonitor');" }, \
(lsp::CompletionItem) { .label = "reqExternalProfile", .insertText = "const ExternalProfile = require('dw/customer/ExternalProfile');" }, \
(lsp::CompletionItem) { .label = "reqCustomerMgr", .insertText = "const CustomerMgr = require('dw/customer/CustomerMgr');" }, \
(lsp::CompletionItem) { .label = "reqProductSearchRefinements", .insertText = "const ProductSearchRefinements = require('dw/catalog/ProductSearchRefinements');" }, \
(lsp::CompletionItem) { .label = "reqCookie", .insertText = "const Cookie = require('dw/web/Cookie');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentIntent", .insertText = "const SalesforcePaymentIntent = require('dw/extensions/payments/SalesforcePaymentIntent');" }, \
(lsp::CompletionItem) { .label = "reqEncryptedObject", .insertText = "const EncryptedObject = require('dw/customer/EncryptedObject');" }, \
(lsp::CompletionItem) { .label = "reqFreeShippingDiscount", .insertText = "const FreeShippingDiscount = require('dw/campaign/FreeShippingDiscount');" }, \
(lsp::CompletionItem) { .label = "reqObjectTypeDefinition", .insertText = "const ObjectTypeDefinition = require('dw/object/ObjectTypeDefinition');" }, \
(lsp::CompletionItem) { .label = "reqStringUtils", .insertText = "const StringUtils = require('dw/util/StringUtils');" }, \
(lsp::CompletionItem) { .label = "reqCampaignStatusCodes", .insertText = "const CampaignStatusCodes = require('dw/campaign/CampaignStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqGiftCertificateStatusCodes", .insertText = "const GiftCertificateStatusCodes = require('dw/order/GiftCertificateStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceVenmoPaymentDetails", .insertText = "const SalesforceVenmoPaymentDetails = require('dw/extensions/payments/SalesforceVenmoPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqFormElementValidationResult", .insertText = "const FormElementValidationResult = require('dw/web/FormElementValidationResult');" }, \
(lsp::CompletionItem) { .label = "reqHashMap", .insertText = "const HashMap = require('dw/util/HashMap');" }, \
(lsp::CompletionItem) { .label = "reqReturnCase", .insertText = "const ReturnCase = require('dw/order/ReturnCase');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedCategory", .insertText = "const SuggestedCategory = require('dw/suggest/SuggestedCategory');" }, \
(lsp::CompletionItem) { .label = "reqShippingOrder", .insertText = "const ShippingOrder = require('dw/order/ShippingOrder');" }, \
(lsp::CompletionItem) { .label = "reqProductAttributeModel", .insertText = "const ProductAttributeModel = require('dw/catalog/ProductAttributeModel');" }, \
(lsp::CompletionItem) { .label = "reqSumItem", .insertText = "const SumItem = require('dw/order/SumItem');" }, \
(lsp::CompletionItem) { .label = "reqSite", .insertText = "const Site = require('dw/system/Site');" }, \
(lsp::CompletionItem) { .label = "reqAbstractItem", .insertText = "const AbstractItem = require('dw/order/AbstractItem');" }, \
(lsp::CompletionItem) { .label = "reqProductVariationModel", .insertText = "const ProductVariationModel = require('dw/catalog/ProductVariationModel');" }, \
(lsp::CompletionItem) { .label = "reqMac", .insertText = "const Mac = require('dw/crypto/Mac');" }, \
(lsp::CompletionItem) { .label = "reqFileWriter", .insertText = "const FileWriter = require('dw/io/FileWriter');" }, \
(lsp::CompletionItem) { .label = "reqOrderPaymentInstrument", .insertText = "const OrderPaymentInstrument = require('dw/order/OrderPaymentInstrument');" }, \
(lsp::CompletionItem) { .label = "reqSystemObjectMgr", .insertText = "const SystemObjectMgr = require('dw/object/SystemObjectMgr');" }, \
(lsp::CompletionItem) { .label = "reqJobExecution", .insertText = "const JobExecution = require('dw/job/JobExecution');" }, \
(lsp::CompletionItem) { .label = "reqCustomObjectMgr", .insertText = "const CustomObjectMgr = require('dw/object/CustomObjectMgr');" }, \
(lsp::CompletionItem) { .label = "reqSignature", .insertText = "const Signature = require('dw/crypto/Signature');" }, \
(lsp::CompletionItem) { .label = "reqURLUtils", .insertText = "const URLUtils = require('dw/web/URLUtils');" }, \
(lsp::CompletionItem) { .label = "reqPaymentCard", .insertText = "const PaymentCard = require('dw/order/PaymentCard');" }, \
(lsp::CompletionItem) { .label = "reqProductActiveData", .insertText = "const ProductActiveData = require('dw/catalog/ProductActiveData');" }, \
(lsp::CompletionItem) { .label = "reqPromotionMgr", .insertText = "const PromotionMgr = require('dw/campaign/PromotionMgr');" }, \
(lsp::CompletionItem) { .label = "reqCipher", .insertText = "const Cipher = require('dw/crypto/Cipher');" }, \
(lsp::CompletionItem) { .label = "reqShippingMethod", .insertText = "const ShippingMethod = require('dw/order/ShippingMethod');" }, \
(lsp::CompletionItem) { .label = "reqHTTPFormService", .insertText = "const HTTPFormService = require('dw/svc/HTTPFormService');" }, \
(lsp::CompletionItem) { .label = "reqCustomerGroup", .insertText = "const CustomerGroup = require('dw/customer/CustomerGroup');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceIdealPaymentDetails", .insertText = "const SalesforceIdealPaymentDetails = require('dw/extensions/payments/SalesforceIdealPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqSOAPService", .insertText = "const SOAPService = require('dw/svc/SOAPService');" }, \
(lsp::CompletionItem) { .label = "reqProductListMgr", .insertText = "const ProductListMgr = require('dw/customer/ProductListMgr');" }, \
(lsp::CompletionItem) { .label = "reqFacebookProduct", .insertText = "const FacebookProduct = require('dw/extensions/facebook/FacebookProduct');" }, \
(lsp::CompletionItem) { .label = "reqProductSearchHit", .insertText = "const ProductSearchHit = require('dw/catalog/ProductSearchHit');" }, \
(lsp::CompletionItem) { .label = "reqSimpleExtensible", .insertText = "const SimpleExtensible = require('dw/object/SimpleExtensible');" }, \
(lsp::CompletionItem) { .label = "reqComponentScriptContext", .insertText = "const ComponentScriptContext = require('dw/experience/ComponentScriptContext');" }, \
(lsp::CompletionItem) { .label = "reqVariant", .insertText = "const Variant = require('dw/catalog/Variant');" }, \
(lsp::CompletionItem) { .label = "reqAddressBook", .insertText = "const AddressBook = require('dw/customer/AddressBook');" }, \
(lsp::CompletionItem) { .label = "reqURLRedirectMgr", .insertText = "const URLRedirectMgr = require('dw/web/URLRedirectMgr');" }, \
(lsp::CompletionItem) { .label = "reqObjectAttributeDefinition", .insertText = "const ObjectAttributeDefinition = require('dw/object/ObjectAttributeDefinition');" }, \
(lsp::CompletionItem) { .label = "reqAppeasementItem", .insertText = "const AppeasementItem = require('dw/order/AppeasementItem');" }, \
(lsp::CompletionItem) { .label = "reqPageScriptContext", .insertText = "const PageScriptContext = require('dw/experience/PageScriptContext');" }, \
(lsp::CompletionItem) { .label = "reqProductPriceInfo", .insertText = "const ProductPriceInfo = require('dw/catalog/ProductPriceInfo');" }, \
(lsp::CompletionItem) { .label = "reqCookies", .insertText = "const Cookies = require('dw/web/Cookies');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceEpsPaymentDetails", .insertText = "const SalesforceEpsPaymentDetails = require('dw/extensions/payments/SalesforceEpsPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqVelocity", .insertText = "const Velocity = require('dw/template/Velocity');" }, \
(lsp::CompletionItem) { .label = "reqReader", .insertText = "const Reader = require('dw/io/Reader');" }, \
(lsp::CompletionItem) { .label = "reqOAuthUserInfoResponse", .insertText = "const OAuthUserInfoResponse = require('dw/customer/oauth/OAuthUserInfoResponse');" }, \
(lsp::CompletionItem) { .label = "reqCustomEditor", .insertText = "const CustomEditor = require('dw/experience/CustomEditor');" }, \
(lsp::CompletionItem) { .label = "reqSOAPUtil", .insertText = "const SOAPUtil = require('dw/rpc/SOAPUtil');" }, \
(lsp::CompletionItem) { .label = "reqActiveData", .insertText = "const ActiveData = require('dw/object/ActiveData');" }, \
(lsp::CompletionItem) { .label = "reqURLRedirect", .insertText = "const URLRedirect = require('dw/web/URLRedirect');" }, \
(lsp::CompletionItem) { .label = "reqMappingKey", .insertText = "const MappingKey = require('dw/util/MappingKey');" }, \
(lsp::CompletionItem) { .label = "reqPrintWriter", .insertText = "const PrintWriter = require('dw/io/PrintWriter');" }, \
(lsp::CompletionItem) { .label = "reqStoreGroup", .insertText = "const StoreGroup = require('dw/catalog/StoreGroup');" }, \
(lsp::CompletionItem) { .label = "reqComponentRenderSettings", .insertText = "const ComponentRenderSettings = require('dw/experience/ComponentRenderSettings');" }, \
(lsp::CompletionItem) { .label = "reqProductShippingModel", .insertText = "const ProductShippingModel = require('dw/order/ProductShippingModel');" }, \
(lsp::CompletionItem) { .label = "reqOutputStream", .insertText = "const OutputStream = require('dw/io/OutputStream');" }, \
(lsp::CompletionItem) { .label = "reqImage", .insertText = "const Image = require('dw/experience/image/Image');" }, \
(lsp::CompletionItem) { .label = "reqCustomerCDPData", .insertText = "const CustomerCDPData = require('dw/customer/CustomerCDPData');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentDetails", .insertText = "const SalesforcePaymentDetails = require('dw/extensions/payments/SalesforcePaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqPaymentApiHooks", .insertText = "const PaymentApiHooks = require('dw/extensions/paymentapi/PaymentApiHooks');" }, \
(lsp::CompletionItem) { .label = "reqPinterestOrder", .insertText = "const PinterestOrder = require('dw/extensions/pinterest/PinterestOrder');" }, \
(lsp::CompletionItem) { .label = "reqOrder", .insertText = "const Order = require('dw/order/Order');" }, \
(lsp::CompletionItem) { .label = "reqImageMetaData", .insertText = "const ImageMetaData = require('dw/experience/image/ImageMetaData');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceSepaDebitPaymentDetails", .insertText = "const SalesforceSepaDebitPaymentDetails = require('dw/extensions/payments/SalesforceSepaDebitPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqCertificateRef", .insertText = "const CertificateRef = require('dw/crypto/CertificateRef');" }, \
(lsp::CompletionItem) { .label = "reqPinterestProduct", .insertText = "const PinterestProduct = require('dw/extensions/pinterest/PinterestProduct');" }, \
(lsp::CompletionItem) { .label = "reqCurrency", .insertText = "const Currency = require('dw/util/Currency');" }, \
(lsp::CompletionItem) { .label = "reqResource", .insertText = "const Resource = require('dw/web/Resource');" }, \
(lsp::CompletionItem) { .label = "reqTaxMgr", .insertText = "const TaxMgr = require('dw/order/TaxMgr');" }, \
(lsp::CompletionItem) { .label = "reqAlert", .insertText = "const Alert = require('dw/alert/Alert');" }, \
(lsp::CompletionItem) { .label = "reqInputStream", .insertText = "const InputStream = require('dw/io/InputStream');" }, \
(lsp::CompletionItem) { .label = "reqAspectAttributeValidationException", .insertText = "const AspectAttributeValidationException = require('dw/experience/AspectAttributeValidationException');" }, \
(lsp::CompletionItem) { .label = "reqFolder", .insertText = "const Folder = require('dw/content/Folder');" }, \
(lsp::CompletionItem) { .label = "reqFTPFileInfo", .insertText = "const FTPFileInfo = require('dw/net/FTPFileInfo');" }, \
(lsp::CompletionItem) { .label = "reqKeyRef", .insertText = "const KeyRef = require('dw/crypto/KeyRef');" }, \
(lsp::CompletionItem) { .label = "reqSearchPhraseSuggestions", .insertText = "const SearchPhraseSuggestions = require('dw/suggest/SearchPhraseSuggestions');" }, \
(lsp::CompletionItem) { .label = "reqPersistentObject", .insertText = "const PersistentObject = require('dw/object/PersistentObject');" }, \
(lsp::CompletionItem) { .label = "reqPriceBook", .insertText = "const PriceBook = require('dw/catalog/PriceBook');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceCardPaymentDetails", .insertText = "const SalesforceCardPaymentDetails = require('dw/extensions/payments/SalesforceCardPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqFacebookFeedHooks", .insertText = "const FacebookFeedHooks = require('dw/extensions/facebook/FacebookFeedHooks');" }, \
(lsp::CompletionItem) { .label = "reqRequest", .insertText = "const Request = require('dw/system/Request');" }, \
(lsp::CompletionItem) { .label = "reqBasketMgr", .insertText = "const BasketMgr = require('dw/order/BasketMgr');" }, \
(lsp::CompletionItem) { .label = "reqHTTPFormServiceDefinition", .insertText = "const HTTPFormServiceDefinition = require('dw/svc/HTTPFormServiceDefinition');" }, \
(lsp::CompletionItem) { .label = "reqCustomObject", .insertText = "const CustomObject = require('dw/object/CustomObject');" }, \
(lsp::CompletionItem) { .label = "reqXMLIndentingStreamWriter", .insertText = "const XMLIndentingStreamWriter = require('dw/io/XMLIndentingStreamWriter');" }, \
(lsp::CompletionItem) { .label = "reqProductVariationAttributeValue", .insertText = "const ProductVariationAttributeValue = require('dw/catalog/ProductVariationAttributeValue');" }, \
(lsp::CompletionItem) { .label = "reqService", .insertText = "const Service = require('dw/svc/Service');" }, \
(lsp::CompletionItem) { .label = "reqCustomerAddress", .insertText = "const CustomerAddress = require('dw/customer/CustomerAddress');" }, \
(lsp::CompletionItem) { .label = "reqPaymentHooks", .insertText = "const PaymentHooks = require('dw/order/hooks/PaymentHooks');" }, \
(lsp::CompletionItem) { .label = "reqXMLStreamConstants", .insertText = "const XMLStreamConstants = require('dw/io/XMLStreamConstants');" }, \
(lsp::CompletionItem) { .label = "reqBonusChoiceDiscount", .insertText = "const BonusChoiceDiscount = require('dw/campaign/BonusChoiceDiscount');" }, \
(lsp::CompletionItem) { .label = "reqRecommendation", .insertText = "const Recommendation = require('dw/catalog/Recommendation');" }, \
(lsp::CompletionItem) { .label = "reqFilteringCollection", .insertText = "const FilteringCollection = require('dw/util/FilteringCollection');" }, \
(lsp::CompletionItem) { .label = "reqFormAction", .insertText = "const FormAction = require('dw/web/FormAction');" }, \
(lsp::CompletionItem) { .label = "reqPriceAdjustmentLimitTypes", .insertText = "const PriceAdjustmentLimitTypes = require('dw/order/PriceAdjustmentLimitTypes');" }, \
(lsp::CompletionItem) { .label = "reqOAuthAccessTokenResponse", .insertText = "const OAuthAccessTokenResponse = require('dw/customer/oauth/OAuthAccessTokenResponse');" }, \
(lsp::CompletionItem) { .label = "reqShipment", .insertText = "const Shipment = require('dw/order/Shipment');" }, \
(lsp::CompletionItem) { .label = "reqCustomerContextMgr", .insertText = "const CustomerContextMgr = require('dw/customer/CustomerContextMgr');" }, \
(lsp::CompletionItem) { .label = "reqRandomAccessFileReader", .insertText = "const RandomAccessFileReader = require('dw/io/RandomAccessFileReader');" }, \
(lsp::CompletionItem) { .label = "reqPaymentRequestHooks", .insertText = "const PaymentRequestHooks = require('dw/extensions/paymentrequest/PaymentRequestHooks');" }, \
(lsp::CompletionItem) { .label = "reqCustomAttributes", .insertText = "const CustomAttributes = require('dw/object/CustomAttributes');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedPhrase", .insertText = "const SuggestedPhrase = require('dw/suggest/SuggestedPhrase');" }, \
(lsp::CompletionItem) { .label = "reqClickStreamEntry", .insertText = "const ClickStreamEntry = require('dw/web/ClickStreamEntry');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePayPalOrderAddress", .insertText = "const SalesforcePayPalOrderAddress = require('dw/extensions/payments/SalesforcePayPalOrderAddress');" }, \
(lsp::CompletionItem) { .label = "reqStringWriter", .insertText = "const StringWriter = require('dw/io/StringWriter');" }, \
(lsp::CompletionItem) { .label = "reqSortedMap", .insertText = "const SortedMap = require('dw/util/SortedMap');" }, \
(lsp::CompletionItem) { .label = "reqUUIDUtils", .insertText = "const UUIDUtils = require('dw/util/UUIDUtils');" }, \
(lsp::CompletionItem) { .label = "reqFTPService", .insertText = "const FTPService = require('dw/svc/FTPService');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePayPalPaymentDetails", .insertText = "const SalesforcePayPalPaymentDetails = require('dw/extensions/payments/SalesforcePayPalPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqHttpParameter", .insertText = "const HttpParameter = require('dw/web/HttpParameter');" }, \
(lsp::CompletionItem) { .label = "reqLinkedHashSet", .insertText = "const LinkedHashSet = require('dw/util/LinkedHashSet');" }, \
(lsp::CompletionItem) { .label = "reqProductOptionModel", .insertText = "const ProductOptionModel = require('dw/catalog/ProductOptionModel');" }, \
(lsp::CompletionItem) { .label = "reqOrganizationPreferences", .insertText = "const OrganizationPreferences = require('dw/system/OrganizationPreferences');" }, \
(lsp::CompletionItem) { .label = "reqMap", .insertText = "const Map = require('dw/util/Map');" }, \
(lsp::CompletionItem) { .label = "reqCache", .insertText = "const Cache = require('dw/system/Cache');" }, \
(lsp::CompletionItem) { .label = "reqCouponRedemption", .insertText = "const CouponRedemption = require('dw/campaign/CouponRedemption');" }, \
(lsp::CompletionItem) { .label = "reqProductSuggestions", .insertText = "const ProductSuggestions = require('dw/suggest/ProductSuggestions');" }, \
(lsp::CompletionItem) { .label = "reqABTest", .insertText = "const ABTest = require('dw/campaign/ABTest');" }, \
(lsp::CompletionItem) { .label = "reqStub", .insertText = "const Stub = require('dw/rpc/Stub');" }, \
(lsp::CompletionItem) { .label = "reqCollection", .insertText = "const Collection = require('dw/util/Collection');" }, \
(lsp::CompletionItem) { .label = "reqFormList", .insertText = "const FormList = require('dw/web/FormList');" }, \
(lsp::CompletionItem) { .label = "reqSOAPServiceDefinition", .insertText = "const SOAPServiceDefinition = require('dw/svc/SOAPServiceDefinition');" }, \
(lsp::CompletionItem) { .label = "reqProductAvailabilityLevels", .insertText = "const ProductAvailabilityLevels = require('dw/catalog/ProductAvailabilityLevels');" }, \
(lsp::CompletionItem) { .label = "reqServiceConfig", .insertText = "const ServiceConfig = require('dw/svc/ServiceConfig');" }, \
(lsp::CompletionItem) { .label = "reqFreeDiscount", .insertText = "const FreeDiscount = require('dw/campaign/FreeDiscount');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePayPalOrder", .insertText = "const SalesforcePayPalOrder = require('dw/extensions/payments/SalesforcePayPalOrder');" }, \
(lsp::CompletionItem) { .label = "reqContentSearchModel", .insertText = "const ContentSearchModel = require('dw/content/ContentSearchModel');" }, \
(lsp::CompletionItem) { .label = "reqHTTPClient", .insertText = "const HTTPClient = require('dw/net/HTTPClient');" }, \
(lsp::CompletionItem) { .label = "reqShipmentShippingCost", .insertText = "const ShipmentShippingCost = require('dw/order/ShipmentShippingCost');" }, \
(lsp::CompletionItem) { .label = "reqList", .insertText = "const List = require('dw/util/List');" }, \
(lsp::CompletionItem) { .label = "reqSearchRefinements", .insertText = "const SearchRefinements = require('dw/catalog/SearchRefinements');" }, \
(lsp::CompletionItem) { .label = "reqDiscount", .insertText = "const Discount = require('dw/campaign/Discount');" }, \
(lsp::CompletionItem) { .label = "reqSFTPFileInfo", .insertText = "const SFTPFileInfo = require('dw/net/SFTPFileInfo');" }, \
(lsp::CompletionItem) { .label = "reqPaymentProcessor", .insertText = "const PaymentProcessor = require('dw/order/PaymentProcessor');" }, \
(lsp::CompletionItem) { .label = "reqCategoryAssignment", .insertText = "const CategoryAssignment = require('dw/catalog/CategoryAssignment');" }, \
(lsp::CompletionItem) { .label = "reqSystem", .insertText = "const System = require('dw/system/System');" }, \
(lsp::CompletionItem) { .label = "reqInternalObject", .insertText = "const InternalObject = require('dw/system/InternalObject');" }, \
(lsp::CompletionItem) { .label = "reqCustomerStatusCodes", .insertText = "const CustomerStatusCodes = require('dw/customer/CustomerStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqFile", .insertText = "const File = require('dw/io/File');" }, \
(lsp::CompletionItem) { .label = "reqIterator", .insertText = "const Iterator = require('dw/util/Iterator');" }, \
(lsp::CompletionItem) { .label = "reqStatusItem", .insertText = "const StatusItem = require('dw/system/StatusItem');" }, \
(lsp::CompletionItem) { .label = "reqAuthenticationStatus", .insertText = "const AuthenticationStatus = require('dw/customer/AuthenticationStatus');" }, \
(lsp::CompletionItem) { .label = "reqHTTPService", .insertText = "const HTTPService = require('dw/svc/HTTPService');" }, \
(lsp::CompletionItem) { .label = "reqShippingOrderItem", .insertText = "const ShippingOrderItem = require('dw/order/ShippingOrderItem');" }, \
(lsp::CompletionItem) { .label = "reqCreateBasketFromOrderException", .insertText = "const CreateBasketFromOrderException = require('dw/order/CreateBasketFromOrderException');" }, \
(lsp::CompletionItem) { .label = "reqPinterestOrderHooks", .insertText = "const PinterestOrderHooks = require('dw/extensions/pinterest/PinterestOrderHooks');" }, \
(lsp::CompletionItem) { .label = "reqCatalog", .insertText = "const Catalog = require('dw/catalog/Catalog');" }, \
(lsp::CompletionItem) { .label = "reqServiceCredential", .insertText = "const ServiceCredential = require('dw/svc/ServiceCredential');" }, \
(lsp::CompletionItem) { .label = "reqProductOption", .insertText = "const ProductOption = require('dw/catalog/ProductOption');" }, \
(lsp::CompletionItem) { .label = "reqFormElement", .insertText = "const FormElement = require('dw/web/FormElement');" }, \
(lsp::CompletionItem) { .label = "reqResponse", .insertText = "const Response = require('dw/system/Response');" }, \
(lsp::CompletionItem) { .label = "reqWeakCipher", .insertText = "const WeakCipher = require('dw/crypto/WeakCipher');" }, \
(lsp::CompletionItem) { .label = "reqApplePayHooks", .insertText = "const ApplePayHooks = require('dw/extensions/applepay/ApplePayHooks');" }, \
(lsp::CompletionItem) { .label = "reqCreateOrderException", .insertText = "const CreateOrderException = require('dw/order/CreateOrderException');" }, \
(lsp::CompletionItem) { .label = "reqPercentageOptionDiscount", .insertText = "const PercentageOptionDiscount = require('dw/campaign/PercentageOptionDiscount');" }, \
(lsp::CompletionItem) { .label = "reqContentSearchRefinementDefinition", .insertText = "const ContentSearchRefinementDefinition = require('dw/content/ContentSearchRefinementDefinition');" }, \
(lsp::CompletionItem) { .label = "reqBytes", .insertText = "const Bytes = require('dw/util/Bytes');" }, \
(lsp::CompletionItem) { .label = "reqOrderHooks", .insertText = "const OrderHooks = require('dw/order/hooks/OrderHooks');" }, \
(lsp::CompletionItem) { .label = "reqShipmentShippingModel", .insertText = "const ShipmentShippingModel = require('dw/order/ShipmentShippingModel');" }, \
(lsp::CompletionItem) { .label = "reqCustomer", .insertText = "const Customer = require('dw/customer/Customer');" }, \
(lsp::CompletionItem) { .label = "reqProductLink", .insertText = "const ProductLink = require('dw/catalog/ProductLink');" }, \
(lsp::CompletionItem) { .label = "reqJobStepExecution", .insertText = "const JobStepExecution = require('dw/job/JobStepExecution');" }, \
(lsp::CompletionItem) { .label = "reqProductPriceTable", .insertText = "const ProductPriceTable = require('dw/catalog/ProductPriceTable');" }, \
(lsp::CompletionItem) { .label = "reqCampaign", .insertText = "const Campaign = require('dw/campaign/Campaign');" }, \
(lsp::CompletionItem) { .label = "reqGeolocation", .insertText = "const Geolocation = require('dw/util/Geolocation');" }, \
(lsp::CompletionItem) { .label = "reqWebReference", .insertText = "const WebReference = require('dw/rpc/WebReference');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentsSiteConfiguration", .insertText = "const SalesforcePaymentsSiteConfiguration = require('dw/extensions/payments/SalesforcePaymentsSiteConfiguration');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedProduct", .insertText = "const SuggestedProduct = require('dw/suggest/SuggestedProduct');" }, \
(lsp::CompletionItem) { .label = "reqLogger", .insertText = "const Logger = require('dw/system/Logger');" }, \
(lsp::CompletionItem) { .label = "reqOrderItem", .insertText = "const OrderItem = require('dw/order/OrderItem');" }, \
(lsp::CompletionItem) { .label = "reqGiftCertificateLineItem", .insertText = "const GiftCertificateLineItem = require('dw/order/GiftCertificateLineItem');" }, \
(lsp::CompletionItem) { .label = "reqPromotion", .insertText = "const Promotion = require('dw/campaign/Promotion');" }, \
(lsp::CompletionItem) { .label = "reqProductListItemPurchase", .insertText = "const ProductListItemPurchase = require('dw/customer/ProductListItemPurchase');" }, \
(lsp::CompletionItem) { .label = "reqRegion", .insertText = "const Region = require('dw/experience/Region');" }, \
(lsp::CompletionItem) { .label = "reqLinkedHashMap", .insertText = "const LinkedHashMap = require('dw/util/LinkedHashMap');" }, \
(lsp::CompletionItem) { .label = "reqWebReference2", .insertText = "const WebReference2 = require('dw/ws/WebReference2');" }, \
(lsp::CompletionItem) { .label = "reqProfile", .insertText = "const Profile = require('dw/customer/Profile');" }, \
(lsp::CompletionItem) { .label = "reqSitemapFile", .insertText = "const SitemapFile = require('dw/sitemap/SitemapFile');" }, \
(lsp::CompletionItem) { .label = "reqServiceProfile", .insertText = "const ServiceProfile = require('dw/svc/ServiceProfile');" }, \
(lsp::CompletionItem) { .label = "reqContentSuggestions", .insertText = "const ContentSuggestions = require('dw/suggest/ContentSuggestions');" }, \
(lsp::CompletionItem) { .label = "reqJWE", .insertText = "const JWE = require('dw/crypto/JWE');" }, \
(lsp::CompletionItem) { .label = "reqABTestSegment", .insertText = "const ABTestSegment = require('dw/campaign/ABTestSegment');" }, \
(lsp::CompletionItem) { .label = "reqProductMgr", .insertText = "const ProductMgr = require('dw/catalog/ProductMgr');" }, \
(lsp::CompletionItem) { .label = "reqProductSearchRefinementValue", .insertText = "const ProductSearchRefinementValue = require('dw/catalog/ProductSearchRefinementValue');" }, \
(lsp::CompletionItem) { .label = "reqSession", .insertText = "const Session = require('dw/system/Session');" }, \
(lsp::CompletionItem) { .label = "reqPage", .insertText = "const Page = require('dw/experience/Page');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceBancontactPaymentDetails", .insertText = "const SalesforceBancontactPaymentDetails = require('dw/extensions/payments/SalesforceBancontactPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqFTPClient", .insertText = "const FTPClient = require('dw/net/FTPClient');" }, \
(lsp::CompletionItem) { .label = "reqMessageDigest", .insertText = "const MessageDigest = require('dw/crypto/MessageDigest');" }, \
(lsp::CompletionItem) { .label = "reqABTestMgr", .insertText = "const ABTestMgr = require('dw/campaign/ABTestMgr');" }, \
(lsp::CompletionItem) { .label = "reqTrackingRef", .insertText = "const TrackingRef = require('dw/order/TrackingRef');" }, \
(lsp::CompletionItem) { .label = "reqShippingLineItem", .insertText = "const ShippingLineItem = require('dw/order/ShippingLineItem');" }, \
(lsp::CompletionItem) { .label = "reqStatus", .insertText = "const Status = require('dw/system/Status');" }, \
(lsp::CompletionItem) { .label = "reqCSVStreamWriter", .insertText = "const CSVStreamWriter = require('dw/io/CSVStreamWriter');" }, \
(lsp::CompletionItem) { .label = "reqMediaFile", .insertText = "const MediaFile = require('dw/content/MediaFile');" }, \
(lsp::CompletionItem) { .label = "reqPaymentTransaction", .insertText = "const PaymentTransaction = require('dw/order/PaymentTransaction');" }, \
(lsp::CompletionItem) { .label = "reqSecureRandom", .insertText = "const SecureRandom = require('dw/crypto/SecureRandom');" }, \
(lsp::CompletionItem) { .label = "reqProductOptionValue", .insertText = "const ProductOptionValue = require('dw/catalog/ProductOptionValue');" }, \
(lsp::CompletionItem) { .label = "reqPromotionPlan", .insertText = "const PromotionPlan = require('dw/campaign/PromotionPlan');" }, \
(lsp::CompletionItem) { .label = "reqBonusDiscount", .insertText = "const BonusDiscount = require('dw/campaign/BonusDiscount');" }, \
(lsp::CompletionItem) { .label = "reqCustomSuggestions", .insertText = "const CustomSuggestions = require('dw/suggest/CustomSuggestions');" }, \
(lsp::CompletionItem) { .label = "reqPipeline", .insertText = "const Pipeline = require('dw/system/Pipeline');" }, \
(lsp::CompletionItem) { .label = "reqWallet", .insertText = "const Wallet = require('dw/customer/Wallet');" }, \
(lsp::CompletionItem) { .label = "reqApplePayHookResult", .insertText = "const ApplePayHookResult = require('dw/extensions/applepay/ApplePayHookResult');" }, \
(lsp::CompletionItem) { .label = "reqCouponMgr", .insertText = "const CouponMgr = require('dw/campaign/CouponMgr');" }, \
(lsp::CompletionItem) { .label = "reqURLAction", .insertText = "const URLAction = require('dw/web/URLAction');" }, \
(lsp::CompletionItem) { .label = "reqOrderMgr", .insertText = "const OrderMgr = require('dw/order/OrderMgr');" }, \
(lsp::CompletionItem) { .label = "reqReturnCaseItem", .insertText = "const ReturnCaseItem = require('dw/order/ReturnCaseItem');" }, \
(lsp::CompletionItem) { .label = "reqReturn", .insertText = "const Return = require('dw/order/Return');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentsHooks", .insertText = "const SalesforcePaymentsHooks = require('dw/extensions/payments/SalesforcePaymentsHooks');" }, \
(lsp::CompletionItem) { .label = "reqCreateTemporaryBasketLimitExceededException", .insertText = "const CreateTemporaryBasketLimitExceededException = require('dw/order/CreateTemporaryBasketLimitExceededException');" }, \
(lsp::CompletionItem) { .label = "reqPriceAdjustment", .insertText = "const PriceAdjustment = require('dw/order/PriceAdjustment');" }, \
(lsp::CompletionItem) { .label = "reqInvoice", .insertText = "const Invoice = require('dw/order/Invoice');" }, \
(lsp::CompletionItem) { .label = "reqPageMgr", .insertText = "const PageMgr = require('dw/experience/PageMgr');" }, \
(lsp::CompletionItem) { .label = "reqProductInventoryMgr", .insertText = "const ProductInventoryMgr = require('dw/catalog/ProductInventoryMgr');" }, \
(lsp::CompletionItem) { .label = "reqPaymentInstrument", .insertText = "const PaymentInstrument = require('dw/order/PaymentInstrument');" }, \
(lsp::CompletionItem) { .label = "reqProductShippingLineItem", .insertText = "const ProductShippingLineItem = require('dw/order/ProductShippingLineItem');" }, \
(lsp::CompletionItem) { .label = "reqContentSearchRefinementValue", .insertText = "const ContentSearchRefinementValue = require('dw/content/ContentSearchRefinementValue');" }, \
(lsp::CompletionItem) { .label = "reqObjectAttributeGroup", .insertText = "const ObjectAttributeGroup = require('dw/object/ObjectAttributeGroup');" }, \
(lsp::CompletionItem) { .label = "reqShippingLocation", .insertText = "const ShippingLocation = require('dw/order/ShippingLocation');" }, \
(lsp::CompletionItem) { .label = "reqSalesforcePaymentRequest", .insertText = "const SalesforcePaymentRequest = require('dw/extensions/payments/SalesforcePaymentRequest');" }, \
(lsp::CompletionItem) { .label = "reqXMLStreamWriter", .insertText = "const XMLStreamWriter = require('dw/io/XMLStreamWriter');" }, \
(lsp::CompletionItem) { .label = "reqSalesforceKlarnaPaymentDetails", .insertText = "const SalesforceKlarnaPaymentDetails = require('dw/extensions/payments/SalesforceKlarnaPaymentDetails');" }, \
(lsp::CompletionItem) { .label = "reqSearchStatus", .insertText = "const SearchStatus = require('dw/system/SearchStatus');" }, \
(lsp::CompletionItem) { .label = "reqLocale", .insertText = "const Locale = require('dw/util/Locale');" }, \
(lsp::CompletionItem) { .label = "reqLogNDC", .insertText = "const LogNDC = require('dw/system/LogNDC');" }, \
(lsp::CompletionItem) { .label = "reqRegionRenderSettings", .insertText = "const RegionRenderSettings = require('dw/experience/RegionRenderSettings');" }, \
(lsp::CompletionItem) { .label = "reqWebDAVClient", .insertText = "const WebDAVClient = require('dw/net/WebDAVClient');" }, \
(lsp::CompletionItem) { .label = "reqSourceCodeGroup", .insertText = "const SourceCodeGroup = require('dw/campaign/SourceCodeGroup');" }, \
(lsp::CompletionItem) { .label = "reqNote", .insertText = "const Note = require('dw/object/Note');" }, \
(lsp::CompletionItem) { .label = "reqWeakMac", .insertText = "const WeakMac = require('dw/crypto/WeakMac');" }, \
(lsp::CompletionItem) { .label = "reqURLParameter", .insertText = "const URLParameter = require('dw/web/URLParameter');" }, \
(lsp::CompletionItem) { .label = "reqPinterestAvailability", .insertText = "const PinterestAvailability = require('dw/extensions/pinterest/PinterestAvailability');" }, \
(lsp::CompletionItem) { .label = "reqWSUtil", .insertText = "const WSUtil = require('dw/ws/WSUtil');" }, \
(lsp::CompletionItem) { .label = "reqForm", .insertText = "const Form = require('dw/web/Form');" }, \
(lsp::CompletionItem) { .label = "reqSearchRefinementDefinition", .insertText = "const SearchRefinementDefinition = require('dw/catalog/SearchRefinementDefinition');" }, \
(lsp::CompletionItem) { .label = "reqWeakSignature", .insertText = "const WeakSignature = require('dw/crypto/WeakSignature');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedTerms", .insertText = "const SuggestedTerms = require('dw/suggest/SuggestedTerms');" }, \
(lsp::CompletionItem) { .label = "reqFixedPriceDiscount", .insertText = "const FixedPriceDiscount = require('dw/campaign/FixedPriceDiscount');" }, \
(lsp::CompletionItem) { .label = "reqSitePreferences", .insertText = "const SitePreferences = require('dw/system/SitePreferences');" }, \
(lsp::CompletionItem) { .label = "reqDecimal", .insertText = "const Decimal = require('dw/util/Decimal');" }, \
(lsp::CompletionItem) { .label = "reqCustomerList", .insertText = "const CustomerList = require('dw/customer/CustomerList');" }, \
(lsp::CompletionItem) { .label = "reqHashSet", .insertText = "const HashSet = require('dw/util/HashSet');" }, \
(lsp::CompletionItem) { .label = "reqOAuthLoginFlowMgr", .insertText = "const OAuthLoginFlowMgr = require('dw/customer/oauth/OAuthLoginFlowMgr');" }, \
(lsp::CompletionItem) { .label = "reqFormFieldOptions", .insertText = "const FormFieldOptions = require('dw/web/FormFieldOptions');" }, \
(lsp::CompletionItem) { .label = "reqSuggestModel", .insertText = "const SuggestModel = require('dw/suggest/SuggestModel');" }, \
(lsp::CompletionItem) { .label = "reqAmountDiscount", .insertText = "const AmountDiscount = require('dw/campaign/AmountDiscount');" }, \
(lsp::CompletionItem) { .label = "reqMail", .insertText = "const Mail = require('dw/net/Mail');" }, \
(lsp::CompletionItem) { .label = "reqServiceRegistry", .insertText = "const ServiceRegistry = require('dw/svc/ServiceRegistry');" }, \
(lsp::CompletionItem) { .label = "reqLineItemCtnr", .insertText = "const LineItemCtnr = require('dw/order/LineItemCtnr');" }, \
(lsp::CompletionItem) { .label = "reqOAuthFinalizedResponse", .insertText = "const OAuthFinalizedResponse = require('dw/customer/oauth/OAuthFinalizedResponse');" }, \
(lsp::CompletionItem) { .label = "reqPageMetaData", .insertText = "const PageMetaData = require('dw/web/PageMetaData');" }, \
(lsp::CompletionItem) { .label = "reqHttpParameterMap", .insertText = "const HttpParameterMap = require('dw/web/HttpParameterMap');" }, \
(lsp::CompletionItem) { .label = "reqBonusDiscountLineItem", .insertText = "const BonusDiscountLineItem = require('dw/order/BonusDiscountLineItem');" }, \
(lsp::CompletionItem) { .label = "reqSortingRule", .insertText = "const SortingRule = require('dw/catalog/SortingRule');" }, \
(lsp::CompletionItem) { .label = "reqSecureFilter", .insertText = "const SecureFilter = require('dw/util/SecureFilter');" }, \
(lsp::CompletionItem) { .label = "reqSecureEncoder", .insertText = "const SecureEncoder = require('dw/util/SecureEncoder');" }, \
(lsp::CompletionItem) { .label = "reqMoney", .insertText = "const Money = require('dw/value/Money');" }, \
(lsp::CompletionItem) { .label = "reqProductList", .insertText = "const ProductList = require('dw/customer/ProductList');" }, \
(lsp::CompletionItem) { .label = "reqBrandSuggestions", .insertText = "const BrandSuggestions = require('dw/suggest/BrandSuggestions');" }, \
(lsp::CompletionItem) { .label = "reqFormGroup", .insertText = "const FormGroup = require('dw/web/FormGroup');" }, \
(lsp::CompletionItem) { .label = "reqCreateAgentBasketLimitExceededException", .insertText = "const CreateAgentBasketLimitExceededException = require('dw/order/CreateAgentBasketLimitExceededException');" }, \
(lsp::CompletionItem) { .label = "reqResult", .insertText = "const Result = require('dw/svc/Result');" }, \
(lsp::CompletionItem) { .label = "reqQuantity", .insertText = "const Quantity = require('dw/value/Quantity');" }, \
(lsp::CompletionItem) { .label = "reqProductSearchRefinementDefinition", .insertText = "const ProductSearchRefinementDefinition = require('dw/catalog/ProductSearchRefinementDefinition');" }, \
(lsp::CompletionItem) { .label = "reqSitemapMgr", .insertText = "const SitemapMgr = require('dw/sitemap/SitemapMgr');" }, \
(lsp::CompletionItem) { .label = "reqBasket", .insertText = "const Basket = require('dw/order/Basket');" }, \
(lsp::CompletionItem) { .label = "reqDiscountPlan", .insertText = "const DiscountPlan = require('dw/campaign/DiscountPlan');" }, \
(lsp::CompletionItem) { .label = "reqGiftCertificate", .insertText = "const GiftCertificate = require('dw/order/GiftCertificate');" }, \
(lsp::CompletionItem) { .label = "reqOrderProcessStatusCodes", .insertText = "const OrderProcessStatusCodes = require('dw/order/OrderProcessStatusCodes');" }, \
(lsp::CompletionItem) { .label = "reqContentMgr", .insertText = "const ContentMgr = require('dw/content/ContentMgr');" }, \
(lsp::CompletionItem) { .label = "reqCampaignMgr", .insertText = "const CampaignMgr = require('dw/campaign/CampaignMgr');" }, \
(lsp::CompletionItem) { .label = "reqCacheMgr", .insertText = "const CacheMgr = require('dw/system/CacheMgr');" }, \
(lsp::CompletionItem) { .label = "reqPagingModel", .insertText = "const PagingModel = require('dw/web/PagingModel');" }, \
(lsp::CompletionItem) { .label = "reqISML", .insertText = "const ISML = require('dw/template/ISML');" }, \
(lsp::CompletionItem) { .label = "reqCategoryLink", .insertText = "const CategoryLink = require('dw/catalog/CategoryLink');" }, \
(lsp::CompletionItem) { .label = "reqHTTPRequestPart", .insertText = "const HTTPRequestPart = require('dw/net/HTTPRequestPart');" }, \
(lsp::CompletionItem) { .label = "reqSearchModel", .insertText = "const SearchModel = require('dw/catalog/SearchModel');" }, \
(lsp::CompletionItem) { .label = "reqPriceBookPriceDiscount", .insertText = "const PriceBookPriceDiscount = require('dw/campaign/PriceBookPriceDiscount');" }, \
(lsp::CompletionItem) { .label = "reqLineItem", .insertText = "const LineItem = require('dw/order/LineItem');" }, \
(lsp::CompletionItem) { .label = "reqDateUtils", .insertText = "const DateUtils = require('dw/util/DateUtils');" }, \
(lsp::CompletionItem) { .label = "reqCalculateHooks", .insertText = "const CalculateHooks = require('dw/order/hooks/CalculateHooks');" }, \
(lsp::CompletionItem) { .label = "reqHTTPServiceDefinition", .insertText = "const HTTPServiceDefinition = require('dw/svc/HTTPServiceDefinition');" }, \
(lsp::CompletionItem) { .label = "reqFTPServiceDefinition", .insertText = "const FTPServiceDefinition = require('dw/svc/FTPServiceDefinition');" }, \
(lsp::CompletionItem) { .label = "reqObjectAttributeValueDefinition", .insertText = "const ObjectAttributeValueDefinition = require('dw/object/ObjectAttributeValueDefinition');" }, \
(lsp::CompletionItem) { .label = "reqSeekableIterator", .insertText = "const SeekableIterator = require('dw/util/SeekableIterator');" }, \
(lsp::CompletionItem) { .label = "reqSFTPClient", .insertText = "const SFTPClient = require('dw/net/SFTPClient');" }, \
(lsp::CompletionItem) { .label = "reqFileReader", .insertText = "const FileReader = require('dw/io/FileReader');" }, \
(lsp::CompletionItem) { .label = "reqSortedSet", .insertText = "const SortedSet = require('dw/util/SortedSet');" }, \
(lsp::CompletionItem) { .label = "reqGiftCertificateMgr", .insertText = "const GiftCertificateMgr = require('dw/order/GiftCertificateMgr');" }, \
(lsp::CompletionItem) { .label = "reqCategorySuggestions", .insertText = "const CategorySuggestions = require('dw/suggest/CategorySuggestions');" }, \
(lsp::CompletionItem) { .label = "reqCSVStreamReader", .insertText = "const CSVStreamReader = require('dw/io/CSVStreamReader');" }, \
(lsp::CompletionItem) { .label = "reqJWSHeader", .insertText = "const JWSHeader = require('dw/crypto/JWSHeader');" }, \
(lsp::CompletionItem) { .label = "reqSuggestions", .insertText = "const Suggestions = require('dw/suggest/Suggestions');" }, \
(lsp::CompletionItem) { .label = "reqMimeEncodedText", .insertText = "const MimeEncodedText = require('dw/value/MimeEncodedText');" }, \
(lsp::CompletionItem) { .label = "reqSlotContent", .insertText = "const SlotContent = require('dw/campaign/SlotContent');" }, \
(lsp::CompletionItem) { .label = "reqMapEntry", .insertText = "const MapEntry = require('dw/util/MapEntry');" }, \
(lsp::CompletionItem) { .label = "reqAppeasement", .insertText = "const Appeasement = require('dw/order/Appeasement');" }, \
(lsp::CompletionItem) { .label = "reqTaxGroup", .insertText = "const TaxGroup = require('dw/order/TaxGroup');" }, \
(lsp::CompletionItem) { .label = "reqSuggestedTerm", .insertText = "const SuggestedTerm = require('dw/suggest/SuggestedTerm');" }, \
(lsp::CompletionItem) { .label = "reqCreateCouponLineItemException", .insertText = "const CreateCouponLineItemException = require('dw/order/CreateCouponLineItemException');" }, \
(lsp::CompletionItem) { .label = "reqInvoiceItem", .insertText = "const InvoiceItem = require('dw/order/InvoiceItem');" }, \
(lsp::CompletionItem) { .label = "reqProductInventoryList", .insertText = "const ProductInventoryList = require('dw/catalog/ProductInventoryList');" }, \
(lsp::CompletionItem) { .label = "reqCalendar", .insertText = "const Calendar = require('dw/util/Calendar');" }, \
(lsp::CompletionItem) { .label = "reqAssert", .insertText = "const Assert = require('dw/util/Assert');" }, \
(lsp::CompletionItem) { .label = "reqPort", .insertText = "const Port = require('dw/ws/Port');" }, \
(lsp::CompletionItem) { .label = "reqAbstractItemCtnr", .insertText = "const AbstractItemCtnr = require('dw/order/AbstractItemCtnr');" }, \
(lsp::CompletionItem) { .label = "reqLog", .insertText = "const Log = require('dw/system/Log');" }, \
(lsp::CompletionItem) { .label = "reqContent", .insertText = "const Content = require('dw/content/Content');" }, \
(lsp::CompletionItem) { .label = "reqEncoding", .insertText = "const Encoding = require('dw/crypto/Encoding');" }, \
(lsp::CompletionItem) { .label = "reqVariationGroup", .insertText = "const VariationGroup = require('dw/catalog/VariationGroup');" }, \
(lsp::CompletionItem) { .label = "reqCredentials", .insertText = "const Credentials = require('dw/customer/Credentials');" }, \
(lsp::CompletionItem) { .label = "reqHookMgr", .insertText = "const HookMgr = require('dw/system/HookMgr');" }, \
(lsp::CompletionItem) { .label = "reqTotalFixedPriceDiscount", .insertText = "const TotalFixedPriceDiscount = require('dw/campaign/TotalFixedPriceDiscount');" }, } \
